intranet/apps/api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from apps.api import views as v
from rest_framework_swagger.views import get_swagger_view

app_name = 'module_api'

whost = None
if settings.DEBUG == False:
    whost = settings.PREFIX_URL

schema_view = get_swagger_view(
    title="API Interface for WRC",
    url=whost,
)

urlpatterns = [
    url(r'^$', schema_view, name='root'),
    url(
        r'^metas/',
        include([
            # url(r'^obtener_ventas/$', v.APIGetVentas.as_view(),
            #     name='sql_obtener_ventas'),
            # url(r'^actualizar_marcas/?$', v.APIUpdateMarcas.as_view(),
            #     name='actualizar_marcas'),
            # url(r'^actualizar_concesionarios/?$', v.APIUpdateConcesionarios.as_view(),
            #     name='actualizar_concesionarios'),
            # url(r'^enviar_emails/?$', v.APISendEmailMetas.as_view(),
            #     name='enviar_emails'),
            # url(r'^obtener_empleados/$', v.APIGetEmpleados.as_view(),
            #     name='sql_obtener_empleados'),
            # url(r'^actualizar_empleados/?$', v.APIUpdateEmpleados.as_view(),
            #     name='actualizar_empleados'),
            # url(r'^actualizar_sucursales/?$', v.APIUpdateSucursales.as_view(),
            #     name='actualizar_sucursales'),
            # url(r'^actualizar_areas/?$', v.APIUpdateArea.as_view(),
            #     name='actualizar_areas'),
            # url(r'^actualizar_puestos/?$', v.APIUpdatePuestos.as_view(),
            #     name='actualizar_puestos'),
        ]),
    ),
    url(
        r'^metas_intranet/',
        include([
            # url(r'^metas_obtener_jefes/?$',
            #     v.APIGetJefes.as_view(),
            #     name='metas_obtener_jefes'),
            # url(r'^metas_obtener_empleados/?$',
            #     v.APIMetasEmpleados.as_view(),
            #     name='metas_obtener_empleados'),
            # url(r'^metas_obtener_marcas/?$',
            #     v.APIGetMarcas.as_view(),
            #     name='metas_obtener_marcas'),
        ]),
    ),
    url(
        r'^catalogos_intranet/',
        include([
            url(r'^metas_obtener_estados/?$',
                v.APIGetEstados.as_view(),
                name='metas_obtener_estados'),
            url(r'^metas_obtener_categorias/?$',
                v.APIGetCategorias.as_view(),
                name='metas_obtener_categorias'),
            url(r'^metas_obtener_articulos/?$',
                v.APIGetArticulos.as_view(),
                name='metas_obtener_articulos'),
            url(r'^metas_obtener_tdocumento/?$',
                v.APIGetTipoDocumento.as_view(),
                name='metas_obtener_tdocumento'),
            url(r'^metas_obtener_tdocumento_pago/?$',
                v.APIGetTipoDocumentoPago.as_view(),
                name='metas_obtener_tdocumento_pago'),
            url(r'^metas_obtener_clientes/?$',
                v.APIGetClientes.as_view(),
                name='metas_obtener_clientes'),
            url(r'^metas_obtener_paises/?$',
                v.APIGetPaises.as_view(),
                name='metas_obtener_paises'),
            url(r'^invoice_obtener_estados/?$',
                v.APIGetEstadosInvoice.as_view(),
                name='invoice_obtener_estados'),
            url(r'^catalogos_obtener_usuario_permisos/?$',
                v.APIGetUsuarioPermisos.as_view(),
                name='catalogos_obtener_usuario_permisos'),
            url(r'^catalogos_obtener_perfil_permisos/?$',
                v.APIGetPerfilPermisos.as_view(),
                name='catalogos_obtener_perfil_permisos'),
            url(r'^metas_obtener_tipificaciones/?$',
                v.APIGetTipificacion.as_view(),
                name='metas_obtener_tipificaciones'),
            url(r'^metas_obtener_tipo_invoice/?$',
                v.APIGetTipoInvoice.as_view(),
                name='metas_obtener_tipo_invoice'),
            url(r'^metas_obtener_forma_pago/?$',
                v.APIGetFormaPago.as_view(),
                name='metas_obtener_forma_pago'),
            url(r'^metas_obtener_contactados/?$',
                v.APIGetContactados.as_view(),
                name='metas_obtener_contactados'),
            # added at 2019.09.02
            url(r'^metas_obtener_tipo_seguimiento/?$',
                v.APIGetTipoSeguimiento.as_view(),
                name='metas_obtener_tipo_seguimiento'),
            # added at 2019.09.19
            url(r'^metas_obtener_vendedores/?$',
                v.APIGetVendedores.as_view(),
                name='metas_obtener_vendedores'),
        ]),
    ),
]

intranet/apps/invoice/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from apps.invoice import views as v

app_name = 'module_invoice'

urlpatterns = [
    url(r'^$', v.ViewInvoice.as_view(), name='main'),
    url(r'^backoffice/$', v.ViewBackOffice.as_view(), name='backoffice'),
    # url(r'^articles/$', v.ViewArticlesView.as_view(), name='articles'),
]

intranet/intranet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/?', admin.site.urls),
    url(r'^login/', include('apps.login.urls', namespace='login'),),
    url(r'^main/', include('apps.main.urls', namespace='main'),),
    url(r'^api/v1/', include('apps.api.urls', namespace='apiv1'),),
    url(r'^mail/', include('apps.mail.urls', namespace='mail'),),
    url(r'^invoice/', include('apps.invoice.urls', namespace='invoice'),),
    url(r'^productos/', include('apps.productos.urls', namespace='productos'),),
    url(r'^catalogos/', include('apps.catalogos.urls', namespace='catalogos'),),
    url(r'^grants/', include('apps.grants.urls', namespace='grants'),),
    url(r'^$', RedirectView.as_view(url='login/', permanent=False)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

intranet/apps/invoice/views.py
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.response import Response
from rest_framework.views import APIView
from django.http import JsonResponse
from django.db.models import (
    Value, Case, When, CharField, Q,
    F, Count, Sum, Avg,
    Prefetch, IntegerField,
)
from apps.connections.config import (
    MYSQLConnection,
)

import json
from datetime import datetime

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import (
    login_required,
    permission_required,
)
from django.core.exceptions import PermissionDenied
from apps.productos import models as mdlprod
from apps.invoice import (
    models as mdls,
    serializers as srlz,
    forms as frm,
)

from apps.catalogos import (
    models as mdlcat,
)
from apps.invoice import utils as utl

# Create your views here.


DEFAULT_FORBIDDEN_PAGE = '/login/forbidden'


@method_decorator(login_required, name='dispatch')
class ViewInvoice(View):
    template_name = 'invoices/invoice.html'
    template_header = 'Invoice | Orders'
    template_title = 'Orders'
    defaultResponse = {
        "ok": 1,
        "result": 'Process has been processed successfuly.',
        "status": 200,
    }

    def dispatch(self, *args, **kwargs):
        return super(ViewInvoice, self).dispatch(*args, **kwargs)

    @method_decorator(permission_required(
        'invoice.display_invoiceparent', login_url=DEFAULT_FORBIDDEN_PAGE,),)
    def get(self, request):
        wresponse = self.defaultResponse.copy()
        header = self.template_header
        title = self.template_title
        return render(request, self.template_name, locals())

    def post(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            if not request.is_ajax():
                wresponse['status'] = 400
                raise ValueError(str('Bad Request'))
            if wdata.get("wtype"):
                wtype = wdata.get("wtype")
                if wtype == "add_invoice":
                    return self.addInvoice(request)
                if wtype == "get_invoices":
                    return self.getInvoices(request)
                if wtype == "get_invoice_item":
                    return self.getInvoiceItem(request)
                if wtype == "remove_invoice":
                    return self.removeInvoice(request)
                if wtype == "update_invoice":
                    return self.updateInvoice(request)
                if wtype == "get_xls_invoice":
                    return self.getInvoiceReport(request)
                if wtype == "get_xls_report":
                    return self.getInvoicesReport(request)
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if type(e) is PermissionDenied:
                wresponse['status'], wresponse[
                    'result'] = 403, 'Permission Denied'
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @method_decorator(permission_required('invoice.xlsreport_invoiceparent', raise_exception=True),)
    def getInvoicesReport(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            select_fields = [
                "id", "order", "fhregistro_format",
                "fecha_emision", "cliente_nombre",
                "cliente_phone", "ndetails",
                "fhmodificacion_format", "tipo_invoice",
                "total", "forma_pago", "fecha_entrega",
                "username", "username_modif",
                "forma_pago_descrip", "tipo_descrip",
                "vendedor_nombre",
                "pais_descrip",
                "ciudad_descrip",
                "fecha_entrega_reprogramada",
            ]
            wdata.update({
                "user": request.user, "select_fields": select_fields,
            })
            outcome, err = utl.getXlsInvoiceList(**wdata)
            if err:
                raise ValueError(err)

            srlzdata = srlz.InvoiceParentSerializer(
                outcome, fields=select_fields, many=True,
            ).data
            wreport, werror = utl.get_xls_report(request, srlzdata)
            if werror:
                raise ValueError(str(werror))
            wresponse["result"] = wreport
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @method_decorator(permission_required('invoice.xlsinvoice_invoiceparent', raise_exception=True),)
    def getInvoiceReport(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            winvoice = wdata.get('uid') or ''
            if winvoice == '':
                wresponse['status'] = 400
                raise ValueError(str('Bad Request'))
            Qfilters = Q(id=int(winvoice))
            wqueryset = mdls.InvoiceParent.objects.filter(Qfilters)
            if not wqueryset.exists:
                wresponse['status'] = 400
                raise ValueError(str('Error, invalid Invoice ID specified.'))
            wsource = srlz.InvoiceParentSerializer(wqueryset.get()).data
            for item in wsource.get("invoicedetails_set"):
                item["article_description"] = item.get(
                    "article").get("descripcion")
            wreport, werror = utl.get_xls_invoice(request, wsource)
            if werror:
                raise ValueError(str(werror))
            wresponse['result'] = wreport
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    def getInvoiceItem(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            winvoice = wdata.get('id') or ''
            if winvoice == '':
                wresponse['status'] = 400
                raise ValueError(str('Bad Request'))
            Qfilters = Q(id=int(winvoice))

            qsdetails = mdls.InvoiceDetails.objects.all() \
                .select_related("article__categoria__estado")
            qstipodoc = mdlcat.TipoDocumento.objects.all() \
                .select_related("estado")
            qscliente = mdlcat.Clientes.objects.all() \
                .select_related("estado") \
                .prefetch_related(Prefetch(
                    "tdoc", queryset=qstipodoc,
                ))

            wqueryset = mdls.InvoiceParent.objects.filter(Qfilters) \
                .select_related("estado") \
                .prefetch_related(Prefetch("cliente", queryset=qscliente)) \
                .prefetch_related(Prefetch(
                    "invoicedetails_set", queryset=qsdetails,
                ))

            fields = [
                "id", "cliente", "fhregistro", "fhmodificacion",
                "order", "cliente_phone", "cliente_phone2",
                "cliente_address", "cliente_country", "total",
                "observaciones", "fecha_venta", "fecha_entrega",
                "tipo_invoice", "forma_pago", "estado",
                "nro_tarjeta", "invoicedetails_set",
                "observaciones2", "contesta_celular", "labora",
                "hora_entrega", "vendedor",
                "fecha_etd_courier", "fecha_recepcion",
                "tarjeta_cvv", "tarjeta_vigencia",
                "hora_entrega_hasta",
                "delivery_address",
            ]
            if not wqueryset.exists:
                wresponse['status'] = 400
                raise ValueError(str('Error, invalid Invoice ID specified.'))
            woutcome = srlz.InvoiceParentSerializer(
                wqueryset.get(), fields=fields,
            ).data
            for item in woutcome.get("invoicedetails_set"):
                item["check"], item["visible"] = False, True
            wresponse['result'] = woutcome
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @method_decorator(permission_required('invoice.display_invoiceparent', raise_exception=True),)
    def getInvoices(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            page = utl.Validators.getPageParameters()
            wfrom, wto = 0, page.get("size")
            if wdata.get("npage"):
                wto = page.get("size") * int(wdata.get("npage"))
                wfrom = wto - page.get("size")

            select_fields = [
                "id", "fhregistro", "fhmodificacion",
                "cliente_ndoc",
                "subtotal", "igv", "total", "cliente",
                "order", "fecha_emision", "fecha_vigencia",
                "username", "estado", "forma_pago",
                "username_modif",
                "ndetails", "tipo_invoice", "sub_tipo_invoice",
            ]
            wdata.update({

intranet/templates/invoices/backoffice.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}
	 <link rel="stylesheet" href="{% static '/css/backoffice/backoffice_main.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerTabs"  id="vTabs">
		<p>
			<router-link to="/">
				Ordenes
			</router-link>
			<router-link 
				to="/order"> 
				Detalles 
			</router-link>
		</p>
		<router-view 
			@change-page="onChangePage" 
			@close-dialog="onCloseDialog">
		</router-view>
	</div>

	<div id="container-requests">
		<div class="layerData" id="vContainer" >
			<div class="row layerFields">
				{% include 'invoices/filters/filter_backoffice.html' %}
			</div>
			<div class="layerTable">
				{% include 'invoices/tables/table_backoffice.html' %}
			</div>
			<div class="pager">
			  <el-pagination
			    :page-size="list.page.page_size"
			    :pager-count="list.page.page_count"
			    :current-page="list.page.page_current"
			    layout="prev, pager, next"
			    @current-change="handleChangePage"
			    :total="list.page.page_total">
			  </el-pagination>
			</div>
			<div class="summary">
				<div>
					<span>Total Registros : </span>
					<label> 
						${totales.filas} de ${list.page.page_total}
					</label>
				</div>
			</div>
		</div>
	</div>
	<div id="container-form">
		<div id="vItem">
			{% include 'invoices/forms/form_backoffice.html' %}
		</div>
	</div>

{% endblock %}

{% block additionaljs %}
	<script src="{% static '/js/unpkg.com/vue-router@3.0.1/dist/vue-router.min.js' %}"></script>
	<script type="text/javascript">
		
		const URI_HOME = window.location.pathname ;
		const URI_ESTADO = "{% url 'apiv1:metas_obtener_estados' %}";
		const URI_CATEGORIAS = "{% url 'apiv1:metas_obtener_categorias' %}";
		const URI_ARTICULOS = "{% url 'apiv1:metas_obtener_articulos' %}";
		const URI_TDOCUMENTO = "{% url 'apiv1:metas_obtener_tdocumento' %}";
		const URI_TDOCPAGO = "{% url 'apiv1:metas_obtener_tdocumento_pago' %}";		
		const URI_FPAGO = "{% url 'apiv1:metas_obtener_forma_pago' %}";		
		const URI_CLIENTES = "{% url 'apiv1:metas_obtener_clientes' %}";
		const URI_ESTADOS_VENTA = "{% url 'apiv1:invoice_obtener_estados' %}";
		const URI_TIPO_INV = "{% url 'apiv1:metas_obtener_tipo_invoice' %}";
		const URI_TIPO_SEG = "{% url 'apiv1:metas_obtener_tipo_seguimiento' %}";
	</script>
	<script src="{% static '/js/backoffice_main.js' %}"></script>
{% endblock %}

intranet/templates/invoices/invoice.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}
	 <link rel="stylesheet" href="{% static '/css/invoice_main.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerTabs"  id="vTabs">
		<p>
			<router-link to="/"> Invoices</router-link>
			<!-- <router-link 
				to="/reserva"> 
				Formulario 
			</router-link> -->
		</p>
		<router-view 
			@change-page="onChangePage" 
			@close-dialog="onCloseDialog">
		</router-view>
	</div>

	<div id="container-requests">
		<div class="layerData" id="vContainer" >
			<div class="row layerFields">
				{% include 'invoices/filters/filter_invoice.html' %}
			</div>
			<div class="layerTable">
				{% include 'invoices/tables/table_invoice.html' %}
			</div>
			<div class="pager">
			  <el-pagination
			    :page-size="list.page.page_size"
			    :pager-count="list.page.page_count"
			    :current-page="list.page.page_current"
			    layout="prev, pager, next"
			    @current-change="handleChangePage"
			    :total="list.page.page_total">
			  </el-pagination>
			</div>
			<div class="summary">
				<div>
					<span>Total Registros : </span>
					<label> 
						${totales.filas} de ${list.page.page_total}
					</label>
				</div>
			</div>
		</div>
	</div>
	<div id="container-form">
		<div id="vItem">
			{% include 'invoices/forms/form_invoice.html' %}
		</div>
	</div>

{% endblock %}

{% block additionaljs %}
	<script src="{% static '/js/unpkg.com/vue-router@3.0.1/dist/vue-router.min.js' %}"></script>
	<script type="text/javascript">
		const URI_HOME = window.location.pathname ;
		const URI_ESTADO = "{% url 'apiv1:metas_obtener_estados' %}";
		const URI_CATEGORIAS = "{% url 'apiv1:metas_obtener_categorias' %}";
		const URI_ARTICULOS = "{% url 'apiv1:metas_obtener_articulos' %}";
		const URI_TDOCUMENTO = "{% url 'apiv1:metas_obtener_tdocumento' %}";
		const URI_TDOCPAGO = "{% url 'apiv1:metas_obtener_tdocumento_pago' %}";		
		const URI_FPAGO = "{% url 'apiv1:metas_obtener_forma_pago' %}";		
		const URI_CLIENTES = "{% url 'apiv1:metas_obtener_clientes' %}";
		const URI_ESTADOS_VENTA = "{% url 'apiv1:invoice_obtener_estados' %}";
		const URI_TIPO_INV = "{% url 'apiv1:metas_obtener_tipo_invoice' %}";
		const URI_VENDEDOR = "{% url 'apiv1:metas_obtener_vendedores' %}";
		const uidemployer = '0' ;
	</script>
	<script src="{% static '/js/invoice_main.js' %}"></script>
{% endblock %}