intranet/apps/login/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from apps.login import views as v

app_name = 'module_login'

urlpatterns = [
    url(r'^$', v.LoginView.as_view(), name='main'),
    url(r'^refresh/$', v.RefreshView.as_view(), name='refresh'),
    url(r'^logout/$', v.LogoutView.as_view(), name='logout'),
    url(r'^validation/$', v.LoginValidation.as_view(), name='validation'),
    url(r'^change_password/$', v.LoginChangePasswd.as_view(),
        name='change_password'),
    url(r'^forbidden/$', v.LoginForbidden.as_view(),
        name='forbidden'),
    url(r'^additional_information/$', v.LoginAdditionalInfo.as_view(),
        name='additional_information'),
]

intranet/intranet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/?', admin.site.urls),
    url(r'^login/', include('apps.login.urls', namespace='login'),),
    url(r'^main/', include('apps.main.urls', namespace='main'),),
    url(r'^api/v1/', include('apps.api.urls', namespace='apiv1'),),
    url(r'^mail/', include('apps.mail.urls', namespace='mail'),),
    url(r'^invoice/', include('apps.invoice.urls', namespace='invoice'),),
    url(r'^productos/', include('apps.productos.urls', namespace='productos'),),
    url(r'^catalogos/', include('apps.catalogos.urls', namespace='catalogos'),),
    url(r'^grants/', include('apps.grants.urls', namespace='grants'),),
    url(r'^$', RedirectView.as_view(url='login/', permanent=False)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

intranet/templates/interface/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Invoice Application Login</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" >
	<link rel="stylesheet" type="text/css" href="{% static '/css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/fontawesome-free-5.1.0-web/css/all.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap/4.1.1/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static '/js/unpkg.com/element-ui@2.4.2/lib/theme-chalk/index.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login/login.css' %}">
</head>
<body>
	{% csrf_token %}
	<div class="layer_bg">
		<div class="layer-foreground"></div>
		<figure class="layer-background">
			<img src="{% static '/images/img_bglogin_invoice.jpg' %}">
		</figure>
	</div>
	{% block main %}
	{% endblock %}
	<script type="text/javascript" src="{% static '/js/jquery/jquery-3.3.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static '/css/bootstrap/4.1.1/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sweetalert.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/moment.min.js' %}">
	</script>
	<script type="text/javascript" src="{% static 'js/unpkg.com/axios/axios.min.js' %}">
	</script>
    {% if env %}
		{% comment %} 
    		development 
    		<!-- <script src="{% static '/js/vue/dist/vue.js' %}"></script> -->
			<!-- <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->
    	{% endcomment %}
		<script src="{% static '/js/vue@2.5.17/dist/vue.js' %}"></script>
	{%else%}
		{% comment %} 
			production 
			<!-- <script src="{% static '/js/vue/vue.js' %}"></script> -->
			<!-- <script src="https://cdn.jsdelivr.net/npm/vue"></script> -->
		{% endcomment %}
		<script src="{% static '/js/vue@2.5.17/vue.min.js' %}"></script>
	{%endif%}
	<script src="{% static '/js/unpkg.com/vue-router@3.0.1/dist/vue-router.min.js' %}"></script>
	<script src="{% static '/js/unpkg.com/element-ui@2.4.2/lib/index.js' %}"></script>
	<script src="{% static '/js/unpkg.com/element-ui@2.4.2/lib/umd/locale/es.js' %}"></script>
	<script type="text/javascript">
		ELEMENT.locale(ELEMENT.lang.es)
		axios.defaults.headers.common = {
		    'X-Requested-With': 'XMLHttpRequest',
		    'X-CSRFToken' : document.getElementsByName("csrfmiddlewaretoken")[0].value,
		};
		const axiosPostHeaders = {
			'Content-Type': 'application/x-www-form-urlencoded',
		} ;
		const URI_HOME = window.location.pathname ;
		const URI_VALIDATION = "{% url 'login:validation' %}" ;
	</script>
	<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</body>
</html>

intranet/templates/interface/base_main.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<title>
		{% block title %}
			Invoice Main Interface
		{% endblock %}
	</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" >
	<link rel="stylesheet" type="text/css" href="{% static '/css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/fontawesome-free-5.1.0-web/css/all.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap/4.1.1/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static '/js/unpkg.com/element-ui@2.4.2/lib/theme-chalk/index.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/main/main.css' %}">

	{% block additionalcss %}
    {% endblock %}	
</head>
<body>
	{% csrf_token %}
	{% block main %}
	{% endblock %}
	<script type="text/javascript" src="{% static '/js/jquery/jquery-3.3.1.min.js' %}"></script>
	{% if env %}
		{% comment %} 
    		development 
    		<!-- <script src="{% static '/js/vue/dist/vue.js' %}"></script> -->
			<!-- <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->
    	{% endcomment %}
		<script src="{% static '/js/vue@2.5.17/dist/vue.js' %}"></script>
	{%else%}
		{% comment %} 
			production 
			<!-- <script src="{% static '/js/vue/vue.js' %}"></script> -->
			<!-- <script src="https://cdn.jsdelivr.net/npm/vue"></script> -->
		{% endcomment %}
		<script src="{% static '/js/vue@2.5.17/vue.min.js' %}"></script>
	{%endif%}
	<script src="{% static '/js/unpkg.com/element-ui@2.4.2/lib/index.js' %}"></script>
	<script src="{% static '/js/unpkg.com/element-ui@2.4.2/lib/umd/locale/es.js' %}"></script>
	
	<script type="text/javascript" src="{% static '/css/bootstrap/4.1.1/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/sweetalert.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/moment.min.js' %}">
	</script>
	<script type="text/javascript" 
		src="{% static 'js/unpkg.com/axios/axios.min.js' %}">
	</script>
	<script type="text/javascript" src="{% static 'js/main_utils.js' %}">
    </script>
    <script type="text/javascript" 
    	src="{% static 'js/main.js' %}"></script>

    <script type="text/javascript">
		ELEMENT.locale(ELEMENT.lang.es)
		axios.defaults.headers.common = {
		    'X-Requested-With': 'XMLHttpRequest',
		    'X-CSRFToken' : document.getElementsByName("csrfmiddlewaretoken")[0].value,
		};
		const axiosPostHeaders = {
			'Content-Type': 'application/x-www-form-urlencoded',
		} ;
		var URI_REFRESH = "{% url 'login:refresh' %}" ;
	</script>

    {% block additionaljs %}
    {% endblock %}
</body>
</html>